name: 3dumamba
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - cudatoolkit=11.3.1=h9edb442_10
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=hc01ab50_4
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - ncurses=6.5=h7934f7d_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.24=h0dcde21_1
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - addict==2.4.0
      - aiofiles==22.1.0
      - aiosqlite==0.21.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - argcomplete==3.3.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - argparse==1.4.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - attrs==23.2.0
      - automat==22.10.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.9.0
      - buildtools==1.0.6
      - causal-conv1d==1.2.0.post2
      - certifi==2024.6.2
      - cffi==2.0.0
      - chamfer==2.0.0
      - charset-normalizer==3.3.2
      - click==8.1.8
      - cmake==4.1.2
      - colorlog==6.8.2
      - comm==0.2.3
      - configargparse==1.7.1
      - constantly==23.10.4
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.2.1
      - dash==3.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - distlib==0.3.8
      - docopt==0.6.2
      - easydict==1.13
      - einops==0.8.0
      - entrypoints==0.4
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - flask==3.1.2
      - fonttools==4.53.0
      - fqdn==1.5.1
      - fsspec==2024.6.0
      - furl==2.1.3
      - greenlet==2.0.2
      - h5py==3.14.0
      - huggingface-hub==0.23.3
      - hyperlink==21.0.0
      - idna==3.7
      - importlib-metadata==8.7.0
      - importlib-resources==6.4.0
      - incremental==22.10.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==7.4.9
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-packaging==0.12.3
      - jupyter-server==2.17.0
      - jupyter-server-fileid==0.9.3
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.5
      - lark==1.3.1
      - laspy==2.6.1
      - lit==18.1.6
      - mam==0.0.1
      - mamba-ssm==1.2.0.post1
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - more-itertools==8.7.0
      - mypy-extensions==1.0.0
      - narwhals==2.10.0
      - nbclassic==1.3.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - nox==2024.4.15
      - numpy==1.25.2
      - open3d==0.18.0
      - orderedmultidict==1.0.1
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parse==1.20.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==10.1.0
      - platformdirs==4.2.2
      - plotly==6.3.1
      - prettytable==3.10.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.1
      - pyzmq==27.1.0
      - redo==2.0.4
      - referencing==0.36.2
      - regex==2023.8.8
      - requests==2.32.3
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - safetensors==0.4.1
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - send2trash==1.8.3
      - setuptools==80.9.0
      - setuptools-scm==6.0.1
      - simplejson==3.19.2
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.30
      - stack-data==0.6.3
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - timm==1.0.3
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.13.3
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tornado==6.5.2
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.41.2
      - transforms3d==0.4.2
      - triton==2.0.0
      - twisted==24.3.0
      - typing-extensions==4.12.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.2.1
      - virtualenv==20.26.2
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - y-py==0.6.2
      - ypy-websocket==0.8.4
      - zipp==3.23.0
      - zope-interface==5.4.0
prefix: /home/ramiali/miniconda3/envs/3dumamba
